name: Publish packages

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore -p:Version=${{ github.event.release.tag_name }}
      - name: Pack
        run: dotnet pack --no-build -c Release -p:PackageVersion=${{ github.event.release.tag_name }} -o publish
      - name: Publish
        run: dotnet nuget push publish/*.nupkg --api-key ${{ secrets.NUGET_ORG_TOKEN }} --source "https://api.nuget.org/v3/index.json"

